import time

myhelp = 'You gotta type the number/letters/diggits which is equal to the letter that the IA ask eg: A = S, B = D, . . . . '
x = 'y'

while x == 'y':
    Help = input('Do you want help ? y/n :')
    if Help == ('yes'):
        print(myhelp)
        time.sleep(3)
        AInput = input('A =')
        BInput = input('B =')
        CInput = input('C =')
        DInput = input('D =')
        EInput = input('E =')
        FInput = input('F =')
        GInput = input('G =')
        HInput = input('H =')
        IInput = input('I =')
        JInput = input('J =')
        KInput = input('K =')
        LInput = input('L =')
        MInput = input('M =')
        NInput = input('N =')
        OInput = input('O =')
        PInput = input('P =')
        QInput = input('Q =')
        RInput = input('R =')
        SInput = input('S =')
        TInput = input('T =')
        UInput = input('U =')
        VInput = input('V =')
        WInput = input('W =')
        XInput = input('X =')  
        YInput = input('Y =')
        ZInput = input('Z =')
        MessageToDecode = input('Type the message you want to decode :')   
        DecodedText = MessageToDecode.replace(AInput, 'a').replace(BInput, 'b').replace(CInput, 'c').replace(DInput, 'd').replace(EInput, 'e').replace(FInput, 'f').replace(GInput, 'g').replace(HInput, 'h').replace(IInput, 'i').replace(JInput, 'j').replace(KInput, 'k').replace(LInput, 'l').replace(MInput, 'm').replace(NInput, 'n').replace(OInput, 'o').replace(PInput, 'p').replace(QInput, 'q').replace(TInput, 't').replace(UInput, 'u').replace(VInput, 'v').replace(WInput, 'w').replace(XInput, 'x').replace(YInput, 'y').replace(ZInput, 'z')
        print(DecodedText)
        x = input('Do you wanna encode another message ? y/n :')
        print("\n")    
    elif Help:
        AInput = input('A =')
        BInput = input('B =')
        CInput = input('C =')
        DInput = input('D =')
        EInput = input('E =')
        FInput = input('F =')
        GInput = input('G =')
        HInput = input('H =')
        IInput = input('I =')
        JInput = input('J =')
        KInput = input('K =')
        LInput = input('L =')
        MInput = input('M =')
        NInput = input('N =')
        OInput = input('O =')
        PInput = input('P =')
        QInput = input('Q =')
        RInput = input('R =')
        SInput = input('S =')
        TInput = input('T =')
        UInput = input('U =')
        VInput = input('V =')
        WInput = input('W =')
        XInput = input('X =')  
        YInput = input('Y =')
        ZInput = input('Z =')
        MessageToDecode = input('Type the message you want to decode :')   
        DecodedText = MessageToDecode.replace(AInput, 'a').replace(BInput, 'b').replace(CInput, 'c').replace(DInput, 'd').replace(EInput, 'e').replace(FInput, 'f').replace(GInput, 'g').replace(HInput, 'h').replace(IInput, 'i').replace(JInput, 'j').replace(KInput, 'k').replace(LInput, 'l').replace(MInput, 'm').replace(NInput, 'n').replace(OInput, 'o').replace(PInput, 'p').replace(QInput, 'q').replace(TInput, 't').replace(UInput, 'u').replace(VInput, 'v').replace(WInput, 'w').replace(XInput, 'x').replace(YInput, 'y').replace(ZInput, 'z')
        print(DecodedText)
        x = input('Do you wanna encode another message ? y/n :')
        print("\n") 
else:
    quit()